### ISSUE TITLE
CircleCI and pipelines

### ISSUE THREAD

**Issue by eridem** [GinesSanchez/TestLeoVegas#2]
Hello!

We tested this assignment with an external CI using Travis. We did not get any trouble with it. At least on the test step (not creating an archive).

I am wonder which problem you got when installing the PODs.
Could it be related with SSH keys? Is this repository private?

**Comment by GinesSanchez** [comment]
Hello, Miguel.

The problem was when CI tries to install the PODs. I have not worked too
much with CI before, I tried a couple of hours different config files but
they didn't work.

The repository is public.

**Comment by eridem** [comment]
Oki doki.
