### ISSUE TITLE
We will start revising the code :-)

### ISSUE THREAD

**Issue by eridem** [GinesSanchez/TestLeoVegas#3]
Hola! We will start revising the code.
It will take few days so we can ask the right questions on the interview.

When it is time for the technical review, remember to bring your computer with everything set up, so we can have some live coding fun ;-)

You can do any changes from today to the day we meet up (if you wish to do a last minute clean up or change). Although, we will revise from `259b23973f2575a185af5d875e7c978a1ce508b1`.

Another quick question, do you work with GitHub in your previous or current company?

![source](https://user-images.githubusercontent.com/436978/86583433-90d94300-bf83-11ea-87ed-9ed6d8ef466f.gif)

**Comment by GinesSanchez** [comment]
Hola :D

I've been working with Github the last four years. Since I moved to
Stockholm.

I think I'm going to keep the code as it is. It has been a long code test xD

If you have any more questions, please let me know.

Gracias por todo.

Saludos

**Comment by eridem** [comment]
@GinesSanchez , I am wonder if you could publicizing your private contributions on your GitHub profile.

Publicizing your private contributions does not show your company code in any way, it just give an overview of your commits and work in companies. Here is a link that explain how to enable it:

https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/publicizing-or-hiding-your-private-contributions-on-your-profile

**Comment by GinesSanchez** [comment]
Hello, Miguel.

I used a specific account for each company and I don't have access to them
right now. Not my personal one. So, you will only see the code tests I have
been working on in the last months.

If you want, I can send you references from my last two companies: Voi and
Kaching.

**Comment by eridem** [comment]
If you know the previous username you used in your previous companies, we can have a look if it was activated.
Of course, if you can send me some references, it could be awesome.

My company email is: miguel.coloma@leovegas.com
